apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.lowjungxuan.dpdns.org
  kustomize.buildOptions: --enable-helm
  oidc.config: |
    name: Keycloak
    issuer: https://keycloak.lowjungxuan.dpdns.org/realms/master
    clientID: global
    clientSecret: $argocd-keycloak-oidc:clientSecret
    requestedScopes: ["openid", "profile", "email"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  server.insecure: "true"
  redis.server: redis.infra.svc.cluster.local:6379
  redis.password: $argocd-redis:auth
  redis.compression: gzip
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: role:admin
  scopes: '[preferred_username, email]'
