apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grim-app-secret
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: grim-app-secret
  refreshAfter: 30s
  destination:
    name: grim-app-secret
    create: true
    overwrite: true
  rolloutRestartTargets:
    - kind: Deployment
      name: grim-app
