apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: litellm-secret
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: grim-k8s
  refreshAfter: 30s
  destination:
    name: litellm-secret
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        LITELLM_MASTER_KEY:
          text: '{{ get .Secrets "LITELLM_MASTER_KEY" }}'
        LITELLM_SALT_KEY:
          text: '{{ get .Secrets "LITELLM_SALT_KEY" }}'
        DATABASE_URL:
          text: '{{ get .Secrets "DATABASE_URL" }}'
        REDIS_HOST:
          text: '{{ get .Secrets "REDIS_HOST" }}'
        REDIS_PORT:
          text: '{{ get .Secrets "REDIS_PORT" }}'
        REDIS_PASSWORD:
          text: '{{ get .Secrets "REDIS_PASSWORD" }}'
        OPENAI_API_KEY:
          text: '{{ get .Secrets "OPENAI_API_KEY" }}'
        DEEPSEEK_API_KEY:
          text: '{{ get .Secrets "DEEPSEEK_API_KEY" }}'
        OPENROUTER_API_KEY:
          text: '{{ get .Secrets "OPENROUTER_API_KEY" }}'
        NVIDIA_NIM_API_KEY:
          text: '{{ get .Secrets "NVIDIA_NIM_API_KEY" }}'
        GENERIC_CLIENT_ID:
          text: '{{ get .Secrets "OIDC_CLIENT_ID" }}'
        GENERIC_CLIENT_SECRET:
          text: '{{ get .Secrets "OIDC_CLIENT_SECRET" }}'
        GENERIC_AUTHORIZATION_ENDPOINT:
          text: https://keycloak.lowjungxuan.dpdns.org/realms/master/protocol/openid-connect/auth
        GENERIC_TOKEN_ENDPOINT:
          text: https://keycloak.lowjungxuan.dpdns.org/realms/master/protocol/openid-connect/token
        GENERIC_USERINFO_ENDPOINT:
          text: https://keycloak.lowjungxuan.dpdns.org/realms/master/protocol/openid-connect/userinfo
        GENERIC_SCOPE:
          text: openid profile email
        PROXY_BASE_URL:
          text: https://litellm.lowjungxuan.dpdns.org
