apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: server-secret
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: grim-k8s
  refreshAfter: 30s
  destination:
    name: server-secret
    create: true
    overwrite: true
  rolloutRestartTargets:
    - kind: StatefulSet
      name: postgres
    - kind: StatefulSet
      name: redis
    - kind: StatefulSet
      name: minio
    - kind: Deployment
      name: keycloak
