apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: zealot-secret
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: grim-k8s
  refreshAfter: 30s
  destination:
    name: zealot-secret
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        SECRET_KEY_BASE:
          text: '{{ get .Secrets "ZEALOT_SECRET_KEY_BASE" }}'
        ZEALOT_ADMIN_EMAIL:
          text: '{{ get .Secrets "ZEALOT_ADMIN_EMAIL" }}'
        ZEALOT_ADMIN_PASSWORD:
          text: '{{ get .Secrets "ZEALOT_ADMIN_PASSWORD" }}'
        ZEALOT_POSTGRES_PASSWORD:
          text: '{{ get .Secrets "POSTGRES_PASSWORD" }}'
        REDIS_URL:
          text: 'redis://:{{ get .Secrets "REDIS_PASSWORD" }}@redis.infra.svc.cluster.local:6379/1'
