apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: server-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: server-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: grim-k8s
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: grim-k8s
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: grim-k8s
        property: POSTGRES_DB
    - secretKey: KEYCLOAK_DB_PASSWORD
      remoteRef:
        key: grim-k8s
        property: KEYCLOAK_DB_PASSWORD
    - secretKey: VAULT_DB_PASSWORD
      remoteRef:
        key: grim-k8s
        property: VAULT_DB_PASSWORD
    - secretKey: VAULT_PG_CONNECTION_URL
      remoteRef:
        key: grim-k8s
        property: VAULT_PG_CONNECTION_URL
    - secretKey: KC_DB
      remoteRef:
        key: grim-k8s
        property: KC_DB
    - secretKey: KC_DB_URL
      remoteRef:
        key: grim-k8s
        property: KC_DB_URL
    - secretKey: KC_DB_USERNAME
      remoteRef:
        key: grim-k8s
        property: KC_DB_USERNAME
    - secretKey: KEYCLOAK_ADMIN
      remoteRef:
        key: grim-k8s
        property: KEYCLOAK_ADMIN
    - secretKey: KEYCLOAK_ADMIN_PASSWORD
      remoteRef:
        key: grim-k8s
        property: KEYCLOAK_ADMIN_PASSWORD
    - secretKey: KEYCLOAK_USER_USERNAME
      remoteRef:
        key: grim-k8s
        property: KEYCLOAK_USER_USERNAME
    - secretKey: KEYCLOAK_USER_PASSWORD
      remoteRef:
        key: grim-k8s
        property: KEYCLOAK_USER_PASSWORD
    - secretKey: KEYCLOAK_USER_EMAIL
      remoteRef:
        key: grim-k8s
        property: KEYCLOAK_USER_EMAIL
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: grim-k8s
        property: OIDC_CLIENT_ID
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: grim-k8s
        property: OIDC_CLIENT_SECRET
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: grim-k8s
        property: REDIS_PASSWORD
    - secretKey: ARGOCD_OIDC_CLIENT_ID
      remoteRef:
        key: grim-k8s
        property: ARGOCD_OIDC_CLIENT_ID
    - secretKey: ARGOCD_OIDC_CLIENT_SECRET
      remoteRef:
        key: grim-k8s
        property: ARGOCD_OIDC_CLIENT_SECRET
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: grim-k8s
        property: MINIO_ROOT_USER
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: grim-k8s
        property: MINIO_ROOT_PASSWORD
    - secretKey: MINIO_OIDC_CLIENT_ID
      remoteRef:
        key: grim-k8s
        property: MINIO_OIDC_CLIENT_ID
    - secretKey: MINIO_OIDC_CLIENT_SECRET
      remoteRef:
        key: grim-k8s
        property: MINIO_OIDC_CLIENT_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grim-app-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: grim-app-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: grim-app
