apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: server-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: server-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: grim-k8s
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grim-app-secret
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: grim-app-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: grim-app-secret
