apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.3.6/manifests/install.yaml
  - external-secrets.yaml
  - ingress.yaml

patches:
  - path: patches/delete-bundled-redis.yaml
  - path: patches/argocd-cm.yaml
  - path: patches/argocd-cmd-params-cm.yaml
  - path: patches/argocd-rbac-cm.yaml
  - path: patches/tolerations.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=argocd
  - path: patches/tolerations-statefulset.yaml
    target:
      kind: StatefulSet
      labelSelector: app.kubernetes.io/part-of=argocd
