apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.4.1/manifests/install.yaml
  - vault-secrets.yaml
  - ingress.yaml

patches:
  - path: patches/config.yaml
  - path: patches/tolerations.yaml
    target:
      kind: (Deployment|StatefulSet)
      labelSelector: app.kubernetes.io/part-of=argocd
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
    target:
      kind: Deployment
      name: argocd-applicationset-controller
      version: v1
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
    target:
      kind: Deployment
      name: argocd-dex-server
      version: v1
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
    target:
      kind: Deployment
      name: argocd-notifications-controller
      version: v1
  - patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: argocd-application-controller
      spec:
        template:
          spec:
            containers:
              - name: argocd-application-controller
                resources:
                  requests:
                    cpu: 100m
                    memory: 256Mi
                  limits:
                    cpu: 500m
                    memory: 768Mi
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: argocd-repo-server
      spec:
        template:
          spec:
            containers:
              - name: argocd-repo-server
                resources:
                  requests:
                    cpu: 50m
                    memory: 128Mi
                  limits:
                    cpu: 500m
                    memory: 512Mi
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: argocd-server
      spec:
        template:
          spec:
            containers:
              - name: argocd-server
                resources:
                  requests:
                    cpu: 50m
                    memory: 128Mi
                  limits:
                    cpu: 500m
                    memory: 512Mi
