apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secrets-operator
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault-connection
spec:
  address: http://vault.infra.svc.cluster.local:8200
  skipTLSVerify: false
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vso-grim-k8s
    serviceAccount: vault-secrets-operator
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-redis
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: grim-k8s
  refreshAfter: 30s
  destination:
    name: argocd-redis
    create: true
    transformation:
      excludeRaw: true
      templates:
        auth:
          text: '{{ get .Secrets "REDIS_PASSWORD" }}'
  rolloutRestartTargets:
    - kind: StatefulSet
      name: argocd-application-controller
    - kind: Deployment
      name: argocd-server
    - kind: Deployment
      name: argocd-repo-server
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-keycloak-oidc
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: grim-k8s
  refreshAfter: 30s
  destination:
    name: argocd-keycloak-oidc
    create: true
    transformation:
      excludeRaw: true
      templates:
        clientSecret:
          text: '{{ get .Secrets "ARGOCD_OIDC_CLIENT_SECRET" }}'
  rolloutRestartTargets:
    - kind: Deployment
      name: argocd-server
