apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grim-k8s
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lowjungxuandev/GRIM-K8S
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
    - group: ""
      kind: Secret
      jqPathExpressions:
        - .metadata.annotations."app.kubernetes.io/managed-by"
        - .metadata.labels."app.kubernetes.io/managed-by"
