apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: 0.32.0
      helm:
        releaseName: vault
        values: |
          ui:
            enabled: true
          server:
            image:
              repository: hashicorp/vault
              tag: 2.0.0
            dataStorage:
              enabled: false
            auditStorage:
              enabled: false
            standalone:
              enabled: true
              config: |
                ui = true
                listener "tcp" {
                  tls_disable     = 1
                  address         = "[::]:8200"
                  cluster_address = "[::]:8201"
                }
                storage "postgresql" {
                  ha_enabled = "true"
                }
                disable_mlock = true
            extraSecretEnvironmentVars:
              - envName: VAULT_PG_CONNECTION_URL
                secretName: server-secret
                secretKey: VAULT_PG_CONNECTION_URL
            tolerations:
              - key: node-role.kubernetes.io/control-plane
                effect: NoSchedule
            ingress:
              enabled: true
              ingressClassName: nginx
              annotations:
                nginx.ingress.kubernetes.io/proxy-body-size: "0"
              hosts:
                - host: vault.lowjungxuan.dpdns.org
              tls:
                - hosts:
                    - vault.lowjungxuan.dpdns.org
                  secretName: vault-tls
    - repoURL: https://github.com/lowjungxuan98/AirEye-Cluster
      targetRevision: main
      path: vault
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: vault-bootstrap-secret
      jsonPointers:
        - /data
