apiVersion: batch/v1
kind: Job
metadata:
  name: ignored-by-kustomize-target
spec:
  template:
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
