apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.14.4/deploy/static/provider/baremetal/deploy.yaml

patches:
  - path: hostnetwork-patch.yaml
    target:
      kind: Deployment
      name: ingress-nginx-controller
  - path: toleration-patch.yaml
    target:
      kind: (Deployment|Job)
      namespace: ingress-nginx
