apiVersion: v1
kind: ConfigMap
metadata:
  name: zealot-config
data:
  ZEALOT_DOMAIN: "zealot.lowjungxuan.dpdns.org"
  ZEALOT_POSTGRES_HOST: "postgres.infra.svc.cluster.local"
  ZEALOT_POSTGRES_PORT: "5432"
  ZEALOT_POSTGRES_USERNAME: "postgres"
  ZEALOT_POSTGRES_DB_NAME: "zealot"
  DEFAULT_LOCALE: "en"
  ZEALOT_APPEARANCE: "light"
  ZEALOT_REGISTER_ENABLED: "false"
  ZEALOT_GUEST_MODE: "false"
  ZEALOT_FORCE_SSL: "false"
