apiVersion: v1
kind: ConfigMap
metadata:
  name: zealot-config
data:
  ZEALOT_DOMAIN: zealot.lowjungxuan.dpdns.org
  DEFAULT_LOCALE: en
  ZEALOT_APPEARANCE: dark

  ZEALOT_REGISTER_ENABLED: "false"
  ZEALOT_LOGIN_ENABLED: "true"
  ZEALOT_GUEST_MODE: "false"
  ZEALOT_FORCE_SSL: "false"

  ZEALOT_POSTGRES_HOST: postgres.infra.svc.cluster.local
  ZEALOT_POSTGRES_PORT: "5432"
  ZEALOT_POSTGRES_DB_NAME: zealot
  ZEALOT_POSTGRES_SSLMODE: disable

  OIDC_ENABLED: "true"
  OIDC_NAME: Keycloak
  OIDC_SCOPE: openid,email,profile
  OIDC_RESPONSE_TYPE: code
  OIDC_UID_FIELD: preferred_username
  OIDC_ISSUER_URL: https://keycloak.lowjungxuan.dpdns.org/realms/master
  OIDC_DISCOVERY: "true"

  ZEALOT_LOG_FORMAT: json
