apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zealot-uploads
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zealot-backup
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
