apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
